name: Documentation

on:
  pull_request:
    branches: [ main ]

jobs:
  latex-compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: dokumentation
        root_file: document.tex
        post_compile: "latexmk -c"
        latexmk_shell_escape: true
    - name: Upload PDF file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: PDF Document
        path: dokumentation/document.pdf