name: Documentation

on: [push]

jobs:
  latex-compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@v0.2.0
      with:
        working_directory: dokumentation
        root_file: document.tex
    - name: Upload PDF file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: PDF Document
        path: dokumentation/document.pdf